import os

os_env = os.environ

SECRET_KEY = 'CHANGEME'

DB_HOST = 'localhost'
DB_PORT = os_env.get('OSF_DB_PORT', 27017)
DB_NAME = 'osf20130903'
DB_USER = None
DB_PASS = None

GRAVATAR_SIZE_PROFILE = 70
GRAVATAR_SIZE_ADD_CONTRIBUTOR = 40
